# https://docs.microsoft.com/azure/devops/pipelines/languages/python

resources:
  containers:
  - container: readthedocs
    image: readthedocs/build:stable

pool:
  vmImage: 'ubuntu-16.04'

container: readthedocs

trigger:
- master
- develop

pr:
- master
- develop

steps:
- script: pip install -r source/requirements.txt
  displayName: 'Install Python Requirements'

- script: sudo apt-get update && sudo apt-get install -qy --force-yes texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended latexmk dvipng
  displayName: 'Install LaTeX'

- script: sudo apt-get install -qy --force-yes graphviz
  displayName: 'Install GraphViz'
  
- script: make html
  displayName: 'Compile Docs'
